package gui;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.awt.Image;
import java.awt.JobAttributes;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FilenameFilter;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.core.MatOfByte;
import org.opencv.core.MatOfRect;
import org.opencv.core.Point;
import org.opencv.core.Rect;
import org.opencv.core.Scalar;
import org.opencv.core.Size;
import org.opencv.videoio.VideoCapture;
import org.opencv.objdetect.CascadeClassifier;
import org.opencv.imgproc.Imgproc;
import org.opencv.imgcodecs.Imgcodecs;
import org.opencv.video.Video;



// for capture
import org.opencv.core.*;
       
//for open an image
import com.googlecode.javacv.CanvasFrame;
import com.googlecode.javacv.FrameGrabber;
import com.googlecode.javacv.OpenCVFrameGrabber;
import com.googlecode.javacv.VideoInputFrameGrabber;
import com.googlecode.javacv.cpp.opencv_core.IplImage;
import com.googlecode.javacv.cpp.opencv_highgui;
import static com.googlecode.javacv.cpp.opencv_highgui.*;
import java.awt.image.BufferedImage;
import java.awt.image.RenderedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;




//class of thread



/**
 *
 * @author shaikat
 */
public class FaceDetection extends javax.swing.JFrame {

    //definition
private DaemonThread myThread = null;
int count=0 ;
VideoCapture webSource= null;
Mat frame=new Mat();
MatOfByte mem= new MatOfByte();
CascadeClassifier faceDetector = new CascadeClassifier(FaceDetection.class .getResource("haarcascade_frontalface_alt.xml").getPath().substring(1));
MatOfRect faceDetections = new MatOfRect();
    



//class of thread
class DaemonThread implements Runnable{
    protected  volatile boolean runnable = false;
    
    @Override
    public void run() {
    synchronized(this){
        while (runnable) {
            try{
            webSource.retrieve(frame);
            Graphics g = jPanel1.getGraphics();
            faceDetector.detectMultiScale(frame, faceDetections);
            for(Rect rect:faceDetections.toArray()){
                Imgproc.rectangle(frame, new Point(rect.x,rect.y), new Point(rect.x+rect.width,rect.y+rect.height),new Scalar(0,255,0));
            
            }
            
            Imgcodecs.imencode(".bmp", frame,mem);
            Image im = ImageIO.read(new ByteArrayInputStream(mem.toArray()));
            BufferedImage buff = (BufferedImage) im;
            if(g.drawImage(buff, 0, 0, getWidth(),getHeight()-150,0,0,buff.getWidth(),buff.getHeight(),null)){
            if(runnable==false){
                System.out.println("Paused.....");
                this.wait();
            }
            }
            
           
            
            }
            catch(Exception ex){
                System.out.println("Error");
            }
        }
    
    
    }
    
    
    }


}
    
    
    
    
    /**
     * Creates new form FaceDetection
     */
    public FaceDetection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        StartBtn = new javax.swing.JButton();
        PauseBtn = new javax.swing.JButton();
        CaptureWebCamBtn = new javax.swing.JButton();
        openAnImageBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );

        StartBtn.setText("Start");
        StartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartBtnActionPerformed(evt);
            }
        });

        PauseBtn.setText("Pause");
        PauseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PauseBtnActionPerformed(evt);
            }
        });

        CaptureWebCamBtn.setText("Capture WebCam Image");
        CaptureWebCamBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaptureWebCamBtnActionPerformed(evt);
            }
        });

        openAnImageBtn.setText("open an Image");
        openAnImageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openAnImageBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(StartBtn)
                .addGap(30, 30, 30)
                .addComponent(PauseBtn)
                .addGap(34, 34, 34)
                .addComponent(CaptureWebCamBtn)
                .addGap(18, 18, 18)
                .addComponent(openAnImageBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartBtn)
                    .addComponent(PauseBtn)
                    .addComponent(CaptureWebCamBtn)
                    .addComponent(openAnImageBtn)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartBtnActionPerformed

        //start button
        webSource = new VideoCapture(0);    //video capture from default ca,
        
        myThread = new DaemonThread();          //create object of thread class
        Thread t= new Thread(myThread);
        t.setDaemon(true);
        myThread.runnable = true;
        t.start();           //start thread
        StartBtn.setEnabled(false);     //deactivate start button
        PauseBtn.setEnabled(true);       ////// activate stop button
        
        
        
        
        
    }//GEN-LAST:event_StartBtnActionPerformed

    private void PauseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PauseBtnActionPerformed
        //pause button
        myThread.runnable = false;
        PauseBtn.setEnabled(false);
        StartBtn.setEnabled(true);
        webSource.release();
    }//GEN-LAST:event_PauseBtnActionPerformed

    private void CaptureWebCamBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaptureWebCamBtnActionPerformed
   
        FrameGrabber grabber = new VideoInputFrameGrabber(0);
try {
    while (true) {
      grabber.start();
      Thread.sleep(1000);
      IplImage  img = grabber.grab();

      if (img != null) {
        cvSaveImage("capture.jpg", img);
        grabber.stop();
      }
    }
} catch (Exception e) {
      e.printStackTrace();
}
        
        
        
        
        /*   OpenCVFrameGrabber grabber = new OpenCVFrameGrabber(0);
        
        
        try {
            
            grabber.start();
            IplImage img = grabber.grab();
            if(img!= null){
                
      
                 cvSaveImage("capture.jpg", img);
                
                 
            }
            
           
            
            
        } catch (FrameGrabber.Exception e) {
        
        } */
    
    }//GEN-LAST:event_CaptureWebCamBtnActionPerformed

    private void openAnImageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openAnImageBtnActionPerformed
        // TODO add your handling code here: 
       IplImage image = cvLoadImage("C:\\Users\\S\\Desktop\\face\\FaceDetection\\capture.jpg");
       final CanvasFrame canvas= new CanvasFrame("demo");
       
       canvas.showImage(image);
       canvas.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_openAnImageBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FaceDetection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CaptureWebCamBtn;
    private javax.swing.JButton PauseBtn;
    private javax.swing.JButton StartBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton openAnImageBtn;
    // End of variables declaration//GEN-END:variables
}
